server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示该module就是注册中心
    fetch-registry: false
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/   #集群模式
      defaultZone: http://eureka7001.com:7001/eureka/   #单机模式
  server:
    #关闭自我保护模式，保证不可用服务被及时剔除
    enable-self-preservation: false
    #eureka server清理无效节点的时间间隔，默认60000毫秒，60s
    eviction-interval-timer-in-ms: 2000

